-- 01_tables.sql
-- Base tables and core constraints for the public schema.
-- Run as a privileged role (for example, postgres/service_role).

BEGIN;

-- Legacy sequence names are preserved to match the current production schema.
CREATE SEQUENCE IF NOT EXISTS public.deck_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.likes_id_seq;

CREATE TABLE IF NOT EXISTS public.positions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  display_name text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT user_profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.videos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  url text,
  file_path text,
  position_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  level smallint,
  CONSTRAINT videos_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions (id) ON DELETE RESTRICT,
  CONSTRAINT videos_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.deck (
  id bigint NOT NULL DEFAULT nextval('public.deck_id_seq'::regclass),
  user_id uuid NOT NULL,
  video_id uuid NOT NULL,
  CONSTRAINT deck_pkey PRIMARY KEY (id),
  CONSTRAINT deck_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT deck_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos (id) ON DELETE CASCADE,
  CONSTRAINT deck_user_video_unique UNIQUE (user_id, video_id)
);

CREATE TABLE IF NOT EXISTS public.favourites (
  id bigint NOT NULL DEFAULT nextval('public.likes_id_seq'::regclass),
  user_id uuid NOT NULL,
  video_id uuid NOT NULL,
  CONSTRAINT likes_pkey PRIMARY KEY (id),
  CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT likes_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.notes (
  user_id uuid NOT NULL,
  video_id uuid NOT NULL,
  note_text text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notes_pkey PRIMARY KEY (user_id, video_id),
  CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT notes_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  status text NOT NULL,
  current_period_end timestamptz,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  raw_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  provider text NOT NULL DEFAULT 'google_play',
  provider_subscription_id text,
  product_id text,
  base_plan_id text,
  offer_id text,
  order_id text,
  purchase_token text,
  acknowledged boolean,
  auto_renewing boolean,
  latest_purchase_at timestamptz,
  canceled_at timestamptz,
  entitlement_source text,
  CONSTRAINT subscriptions_status_check CHECK (
    status IN (
      'trialing',
      'active',
      'past_due',
      'canceled',
      'incomplete',
      'incomplete_expired',
      'unpaid',
      'expired',
      'grace_period',
      'on_hold',
      'paused',
      'revoked',
      'pending'
    )
  )
);

CREATE TABLE IF NOT EXISTS public.billing_provider_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  provider text NOT NULL,
  provider_account_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT billing_provider_accounts_provider_check CHECK (provider IN ('google_play')),
  CONSTRAINT billing_provider_accounts_user_provider_unique UNIQUE (user_id, provider),
  CONSTRAINT billing_provider_accounts_provider_account_unique UNIQUE (provider, provider_account_id)
);

CREATE TABLE IF NOT EXISTS public.billing_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL,
  event_id text NOT NULL,
  event_type text,
  payload jsonb NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT billing_events_provider_check CHECK (provider IN ('google_play')),
  CONSTRAINT billing_events_provider_event_unique UNIQUE (provider, event_id)
);

CREATE TABLE IF NOT EXISTS public.client_error_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  context text NOT NULL,
  message text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Ensure legacy sequences are owned by their columns.
ALTER SEQUENCE IF EXISTS public.deck_id_seq OWNED BY public.deck.id;
ALTER SEQUENCE IF EXISTS public.likes_id_seq OWNED BY public.favourites.id;

COMMIT;
