-- billing_subscription_mvp.sql
-- Minimal billing schema for Stripe subscription MVP.

-- Stores the Stripe customer ID associated with each authenticated app user.
-- This gives webhook processing a stable user <-> Stripe customer mapping.
CREATE TABLE IF NOT EXISTS public.billing_customers (
  user_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  stripe_customer_id text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Stores the latest known subscription state for each Stripe subscription.
-- The raw payload is kept for debugging and support while the key fields drive access checks.
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  stripe_subscription_id text NOT NULL UNIQUE,
  stripe_customer_id text,
  stripe_price_id text,
  status text NOT NULL,
  current_period_end timestamptz,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  raw_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT subscriptions_status_check CHECK (
    status IN ('trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid')
  )
);

-- Speeds up the common lookups used by entitlement checks and webhook updates.
CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS subscriptions_customer_idx ON public.subscriptions (stripe_customer_id);

-- Tracks processed Stripe webhook events so retries do not apply the same change twice.
CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  event_id text PRIMARY KEY,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT now()
);

-- Enable RLS so client-side reads are limited to explicit policies instead of full-table access.
ALTER TABLE public.billing_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read only their own billing customer row and subscription rows.
-- No client policy is added for webhook events because that table is intended for server-side use only.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'billing_customers' AND policyname = 'billing_customers_select_own'
  ) THEN
    CREATE POLICY billing_customers_select_own ON public.billing_customers
      FOR SELECT TO authenticated
      USING (user_id = auth.uid());
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'subscriptions' AND policyname = 'subscriptions_select_own'
  ) THEN
    CREATE POLICY subscriptions_select_own ON public.subscriptions
      FOR SELECT TO authenticated
      USING (user_id = auth.uid());
  END IF;
END $$;

-- Grant read access for the tables that the mobile app needs to query directly.
GRANT SELECT ON public.billing_customers TO authenticated;
GRANT SELECT ON public.subscriptions TO authenticated;

-- Central helper used by the app and future RLS policies to answer one question:
-- does this user currently have subscription-based access?
CREATE OR REPLACE FUNCTION public.has_active_subscription(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.subscriptions s
    WHERE s.user_id = p_user_id
      AND s.status IN ('trialing', 'active')
      AND (s.current_period_end IS NULL OR s.current_period_end > now())
  );
$$;

-- Allow authenticated app clients to call the access helper safely.
GRANT EXECUTE ON FUNCTION public.has_active_subscription(uuid) TO authenticated;