-- client_error_logs.sql
-- Centralized app-side error logging table for auth/billing failure observability.

BEGIN;

CREATE TABLE IF NOT EXISTS public.client_error_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  context text NOT NULL,
  message text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS client_error_logs_created_idx
  ON public.client_error_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS client_error_logs_context_idx
  ON public.client_error_logs (context);

ALTER TABLE public.client_error_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'client_error_logs'
      AND policyname = 'client_error_logs_insert_own'
  ) THEN
    CREATE POLICY client_error_logs_insert_own
      ON public.client_error_logs
      FOR INSERT
      TO authenticated
      WITH CHECK (user_id = auth.uid());
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'client_error_logs'
      AND policyname = 'client_error_logs_select_own'
  ) THEN
    CREATE POLICY client_error_logs_select_own
      ON public.client_error_logs
      FOR SELECT
      TO authenticated
      USING (user_id = auth.uid());
  END IF;
END $$;

GRANT INSERT, SELECT ON public.client_error_logs TO authenticated;

COMMIT;
