-- migrate_stripe_to_google_play_mvp.sql
-- Draft migration to move from Stripe-only billing fields toward a provider-agnostic
-- model that supports Google Play Billing while remaining backward compatible.
--
-- IMPORTANT
-- 1) Run this first in a dev/staging database.
-- 2) Existing Stripe data is preserved.
-- 3) App code can migrate incrementally because old columns are not dropped here.

BEGIN;

-- Provider account mapping table (future-proofed for multiple providers).
CREATE TABLE IF NOT EXISTS public.billing_provider_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  provider text NOT NULL,
  provider_account_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT billing_provider_accounts_provider_check CHECK (provider IN ('stripe', 'google_play')),
  CONSTRAINT billing_provider_accounts_user_provider_unique UNIQUE (user_id, provider),
  CONSTRAINT billing_provider_accounts_provider_account_unique UNIQUE (provider, provider_account_id)
);

CREATE INDEX IF NOT EXISTS billing_provider_accounts_user_idx
  ON public.billing_provider_accounts (user_id);

-- Generic billing event log for idempotency and diagnostics.
CREATE TABLE IF NOT EXISTS public.billing_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL,
  event_id text NOT NULL,
  event_type text,
  payload jsonb NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT billing_events_provider_check CHECK (provider IN ('stripe', 'google_play')),
  CONSTRAINT billing_events_provider_event_unique UNIQUE (provider, event_id)
);

CREATE INDEX IF NOT EXISTS billing_events_processed_idx
  ON public.billing_events (provider, processed_at DESC);

-- Extend subscriptions table to support Google Play Billing while preserving existing Stripe fields.
ALTER TABLE public.subscriptions
  ADD COLUMN IF NOT EXISTS provider text,
  ADD COLUMN IF NOT EXISTS provider_subscription_id text,
  ADD COLUMN IF NOT EXISTS product_id text,
  ADD COLUMN IF NOT EXISTS base_plan_id text,
  ADD COLUMN IF NOT EXISTS offer_id text,
  ADD COLUMN IF NOT EXISTS order_id text,
  ADD COLUMN IF NOT EXISTS purchase_token text,
  ADD COLUMN IF NOT EXISTS acknowledged boolean,
  ADD COLUMN IF NOT EXISTS auto_renewing boolean,
  ADD COLUMN IF NOT EXISTS latest_purchase_at timestamptz,
  ADD COLUMN IF NOT EXISTS canceled_at timestamptz,
  ADD COLUMN IF NOT EXISTS entitlement_source text;

-- Backfill provider-neutral columns from existing Stripe columns.
UPDATE public.subscriptions
SET
  provider = COALESCE(provider, 'stripe'),
  provider_subscription_id = COALESCE(provider_subscription_id, stripe_subscription_id),
  product_id = COALESCE(product_id, stripe_price_id),
  entitlement_source = COALESCE(entitlement_source, 'stripe_webhook')
WHERE provider IS NULL
   OR provider_subscription_id IS NULL
   OR product_id IS NULL
   OR entitlement_source IS NULL;

ALTER TABLE public.subscriptions
  ALTER COLUMN provider SET DEFAULT 'stripe',
  ALTER COLUMN provider SET NOT NULL;

-- Replace Stripe-only status constraint with a provider-agnostic set that still includes Stripe statuses.
ALTER TABLE public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_status_check;

ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_status_check CHECK (
    status IN (
      -- Existing Stripe statuses
      'trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid',
      -- Google Play style states mapped by server
      'expired', 'grace_period', 'on_hold', 'paused', 'revoked', 'pending'
    )
  );

-- Uniqueness/indexes for provider-specific lookups.
CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_provider_subscription_uidx
  ON public.subscriptions (provider, provider_subscription_id)
  WHERE provider_subscription_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_google_play_purchase_token_uidx
  ON public.subscriptions (purchase_token)
  WHERE provider = 'google_play' AND purchase_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS subscriptions_provider_user_idx
  ON public.subscriptions (provider, user_id);

CREATE INDEX IF NOT EXISTS subscriptions_status_period_idx
  ON public.subscriptions (status, current_period_end DESC);

-- Keep has_active_subscription as the single source for entitlement checks.
-- For Google Play, current_period_end should be set from expiryTime in your verifier.
CREATE OR REPLACE FUNCTION public.has_active_subscription(p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.subscriptions s
    WHERE s.user_id = p_user_id
      AND s.status IN ('trialing', 'active', 'grace_period')
      AND (s.current_period_end IS NULL OR s.current_period_end > now())
  );
$$;

GRANT EXECUTE ON FUNCTION public.has_active_subscription(uuid) TO authenticated;

-- RLS for new billing tables.
ALTER TABLE public.billing_provider_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'billing_provider_accounts'
      AND policyname = 'billing_provider_accounts_select_own'
  ) THEN
    CREATE POLICY billing_provider_accounts_select_own ON public.billing_provider_accounts
      FOR SELECT TO authenticated
      USING (user_id = auth.uid());
  END IF;
END $$;

GRANT SELECT ON public.billing_provider_accounts TO authenticated;

COMMIT;
